src/Entity/Author.php
<?php

namespace App\Entity;

use App\Repository\AuthorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AuthorRepository::class)]
class Author
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $username = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    /**
     * @var Collection<int, Book>
     */
    #[ORM\OneToMany(targetEntity: Book::class, mappedBy: 'author', orphanRemoval: true  )]
    private Collection $book;

    #[ORM\Column]
    private ?int $nb_books = null;

    public function __construct()
    {
        $this->book = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection<int, Book>
     */
    public function getBook(): Collection
    {
        return $this->book;
    }

    public function addBook(Book $book): static
    {
        if (!$this->book->contains($book)) {
            $this->book->add($book);
            $book->setAuthor($this);
        }

        return $this;
    }

    public function removeBook(Book $book): static
    {
        if ($this->book->removeElement($book)) {
         
            if ($book->getAuthor() === $this) {
                $book->setAuthor(null);
            }
        }

        return $this;
    }

    public function getNbBooks(): ?int
    {
        return $this->nb_books;
    }

    public function setNbBooks(int $nb_books): static
    {
        $this->nb_books = $nb_books;

        return $this;
    }
}

src/Controller/AuthorcontrollerController.php
<?php

namespace App\Controller;

use App\Entity\Author;
use App\Form\AuthorType;
use App\Repository\AuthorRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class AuthorcontrollerController extends AbstractController
{
    #[Route('/authors', name: 'app_authors')]
    public function index(): Response
    {
        return $this->render('authors/index.html.twig', [
            'controller_name' => 'AuthorsController',
        ]);
    }

      #[Route('/showAuthors', name: 'app_showauthors')]
    public function showauthors(AuthorRepository $authorRepo): Response
    {
        $a= $authorRepo->trieAsc();
        return $this->render('authorcontroller/showauthors.html.twig', [
            'listauthor' => $a,
        ]);
    }


     #[Route('/add', name: 'app_addauthors')]
    public function add(ManagerRegistry $m): Response
    {
        $em=$m->getManager();
        $author=new Author();
        $author->setUsername("oussema");
        $author->setEmail("oussema@esprit.tn");
        $em->persist($author);
        $em->flush();
        return $this->redirectToRoute('app_showauthors');
    }

    //amine jouini: +2
    #[Route('/deleteauthores/{id}', name: 'app_deleteauthors')]
    public function deleteauthores(ManagerRegistry $m ,AuthorRepository $a, $id ): Response
    {
        $em=$m->getManager();
        $f=$a->find($id);
        $em->remove($f);
        $em->flush();
        
        return $this->redirectToRoute('app_showauthors');
    }
    //mehd zouaghi+5
    #[Route('/editauthores/{id}', name: 'app_editauthors')]
    public function editauthores(Request $request, ManagerRegistry $m ,AuthorRepository $a, $id ): Response
    {
        $em=$m->getManager();
        $f=$a->find($id);
        $form=$this->createForm(AuthorType::class,$f);
        if( $form->isSubmitted() && $form->isValid()){
            $form->handleRequest($request);
            $em->persist($f);
            $em->flush();
            return $this->redirectToRoute('app_showauthors');
        }
        
        
        return $this->render('authorcontroller/editauthors.html.twig', [
            'f' => $form,
        ]);

    }
    #[Route('/Addauthores', name: 'addauthors')]
     public function Addauthores(Request $request, ManagerRegistry $m ): Response
    {
        $em=$m->getManager();
        $f=new Author();
        $form=$this->createForm(AuthorType::class,$f);
        
        $form->handleRequest($request);
        if( $form->isSubmitted() && $form->isValid()){
            
            $em->persist($f);
            $em->flush();
            return $this->redirectToRoute('app_showauthors');
        }
        
        
        return $this->render('authorcontroller/Addauthors.html.twig', [
            'f' => $form,
        ]);

    }
    

}

templates/authorcontroller/Addauthors.html.twig
{{form(f)}}

templates/authorcontroller/editauthors.html.twig
{{ form(f)}}

templates/authorcontroller/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AuthorsController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>C:/Users/osema/Desktop/3a44/FirstProject/src/Controller/AuthorsController.php</code></li>
        <li>Your template at <code>C:/Users/osema/Desktop/3a44/FirstProject/templates/authors/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}

templates/authorcontroller/showauthors.html.twig
<table border="3">
    <tr>
        <td>id</td>
        <td>username</td>
        <td>email</td>
        <td>number of books</td>
        <td>delete</td>
        <td>edit</td>

    </tr>
    {% for i in listauthor %}
    <tr>
<td>{{i.id}}</td>
<td>{{i.username}}</td>
<td>{{i.email}}</td>
<td>{{i.nbBooks}}</td>
<td><a href="{{path('app_deleteauthors',{'id':i.id})}}">delete</a></td>
<td><a href="{{path('app_editauthors',{'id':i.id})}}">edit</a></td>
    </tr>
    {% endfor %}
</table>        